--Ejecutar el siguiente script en el ambiente deseado
CREATE TABLE MTI_FACTURACION.FE_OBJETO_IMPUESTO 
(
  OBJETO_KEY NUMBER NOT NULL 
, CLAVE VARCHAR2(20 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(200 BYTE) NOT NULL 
) ;

ALTER TABLE MTI_FACTURACION.FE_OBJETO_IMPUESTO
ADD CONSTRAINT PK_FE_OBJETO_IMPUESTO PRIMARY KEY 
(
  OBJETO_KEY 
);

ALTER TABLE MTI_FACTURACION.FE_OBJETO_IMPUESTO
ADD CONSTRAINT NN_FE_OBJETO_IMPUESTO_02 CHECK 
(CLAVE IS NOT NULL)
ENABLE;

ALTER TABLE MTI_FACTURACION.FE_OBJETO_IMPUESTO
ADD CONSTRAINT NN_FE_OBJETO_IMPUESTO_03 CHECK 
(DESCRIPCION IS NOT NULL)
ENABLE;

COMMENT ON COLUMN MTI_FACTURACION.FE_OBJETO_IMPUESTO.OBJETO_KEY IS 'Llave primaria de la tabla.';
COMMENT ON COLUMN MTI_FACTURACION.FE_OBJETO_IMPUESTO.CLAVE IS 'Identificador de la clave de exportación).';
COMMENT ON COLUMN MTI_FACTURACION.FE_OBJETO_IMPUESTO.DESCRIPCION IS 'Descripción de la exportación.';
/
create sequence MTI_FACTURACION.SEQ_FE_OBJETO_IMPUESTO
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  NOCYCLE
  NOORDER
  NOCACHE;
  /
create TRIGGER MTI_FACTURACION.T_FE_OBJETO_IMPUESTO_BI 
BEFORE INSERT ON MTI_FACTURACION.FE_OBJETO_IMPUESTO
for each row
declare
lnKey Number;
Begin
  Select MTI_FACTURACION.SEQ_FE_OBJETO_IMPUESTO.NEXTVAL
    Into lnKey
    From dual;   

    :new.OBJETO_KEY := lnkey;
end;  
/
Begin
	Insert into MTI_FACTURACION.FE_OBJETO_IMPUESTO (CLAVE,DESCRIPCION) values ('01','No objeto de impuesto.');
	Insert into MTI_FACTURACION.FE_OBJETO_IMPUESTO (CLAVE,DESCRIPCION) values ('02','Sí objeto de impuesto.');
	Insert into MTI_FACTURACION.FE_OBJETO_IMPUESTO (CLAVE,DESCRIPCION) values ('03','Sí objeto del impuesto y no obligado al desglose.');
Commit;
Exception
   When Others Then
      Rollback;
      raise_application_error(-20001,sqlerrm);
End;
